// docs/components/storybook-link.tsx
const STORYBOOK_BASE = 'https://storybook.praxisjs.org';

interface StorybookLinkProps {
  story: string;
  label?: string;
}

export function StorybookLink({ story, label = 'Live demo' }: StorybookLinkProps) {
  const href = `${STORYBOOK_BASE}/?path=/story/${story}`;
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="not-prose group my-4 flex items-center gap-4 rounded-xl border bg-fd-card px-4 py-3 no-underline transition-all duration-200 hover:bg-fd-accent"
      style={{ borderLeftWidth: '3px', borderLeftColor: '#FF4785', borderColor: 'var(--color-fd-border)' }}
    >
      {/* Storybook bookmark icon */}
      <svg
        width="18"
        height="18"
        viewBox="0 0 18 18"
        fill="none"
        aria-hidden
        className="shrink-0"
      >
        <path
          d="M3 2h12v14l-6-4-6 4V2z"
          stroke="#FF4785"
          strokeWidth="1.5"
          strokeLinejoin="round"
        />
        <path
          d="M6.5 7.5h5"
          stroke="#FF4785"
          strokeWidth="1.5"
          strokeLinecap="round"
        />
      </svg>

      <div className="min-w-0 flex-1">
        <div className="text-[10px] font-semibold uppercase tracking-wider" style={{ color: '#FF4785' }}>
          Storybook
        </div>
        <div className="truncate text-sm font-medium text-fd-foreground">
          {label}
        </div>
      </div>

      {/* External link arrow */}
      <svg
        width="13"
        height="13"
        viewBox="0 0 13 13"
        fill="none"
        aria-hidden
        className="shrink-0 text-fd-muted-foreground transition-transform duration-200 group-hover:translate-x-0.5 group-hover:-translate-y-0.5"
      >
        <path
          d="M1 12L12 1M12 1H5M12 1V8"
          stroke="currentColor"
          strokeWidth="1.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    </a>
  );
}

// docs/.vitepress/theme/components/StorybookLink.vue
<script setup lang="ts">
const base = (import.meta.env.VITE_STORYBOOK_URL as string | undefined)?.replace(/\/$/, "") ?? "http://localhost:6006";

const props = defineProps<{
  story: string;
  label?: string;
}>();

const href = `${base}/?path=/story/${props.story}`;
</script>

<template>
  <a :href="href" target="_blank" rel="noopener noreferrer" class="storybook-link">
    <svg width="12" height="12" viewBox="0 0 14 14" fill="none" aria-hidden="true">
      <path d="M1.5 12.5h11V1.5H1.5v11z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
      <path d="M5 5l4 4M9 5L5 9" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
    </svg>
    {{ label ?? "View in Storybook" }}
  </a>
</template>

<style scoped>
.storybook-link {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  padding: 5px 12px;
  border-radius: 6px;
  border: 1px solid var(--vp-c-brand-1);
  color: var(--vp-c-brand-1);
  font-size: 0.82rem;
  font-weight: 600;
  text-decoration: none;
  transition: background 0.15s, color 0.15s;
  white-space: nowrap;
}

.storybook-link:hover {
  background: var(--vp-c-brand-1);
  color: #fff;
}
</style>
